version: '3'
services:
  eureka-server:
    image: eureka-server
    ports:
     - "8761:8761"
  addition:
    image: addition
    ports:
      - "4830:4830"
    depends_on:
      - eureka-server
  multiplication:
    image: multiplication
    ports:
      - "4831:4831"
    depends_on:
      - eureka-server
  simple-calculator:
    image: simple-calculator
    ports:
      - "4832:4832"
    depends_on:
      - addition
      - multiplication
      - eureka-server
